module.exports = {
  AuthController: require("../Client/AuthController"),
  ProfileController: require("../Client/ProfileController"),
  CategoryManagementController: require("../Client/CategoryManagementController"),
  TestController: require("../Client/TestController"),
  ProductController: require("../Client/ProductController"),
  OrderController: require("../Client/OrderController"),
  WishlistController: require("../Client/WishlistController"),
  ReviewController: require("../Client/ReviewController"),
  CountryController: require("../Client/CountryController"),
  SubscriptionPackageController: require("../Client/SubscriptionPackageController"),
  UserSubscriptionController: require("../Client/UserSubscriptionController"),
  WebhookController: require("../Client/WebhookController"),
  TransactionController: require("../Client/TransactionController"),
  StaticPageManagement: require("../Client/StaticPageManagement"),
  CartController: require("../Client/CartController"),
  ContactUsController: require("../Client/ContactUsController"),
  SocialMediaController: require("../Client/Social-mediaController"),
};
