module.exports = {
  UserService: require("./UserService"),
  TokenService: require("./TokenService"),
  RoleService: require("./RoleService"),
  CategoryService: require("./CategoryService"),
  PageService: require("./PageService"),
  SettingService: require("./SettingService"),
  ProductService: require("./ProductService"),
  ProductPriceService: require("./ProductPriceService"),
  ProductDpiService: require("./ProductDpiService"),
  OrderService: require("./OrderService"),
  WishlistService: require("./WishlistService"),
  ReviewService: require("./ReviewService"),
  CountriesService: require("./CountriesService"),
  StatesService: require("./StatesService"),
  PackageTypeService: require("./PackageTypeService"),
  SubscriptionPackageService: require("./SubscriptionPackageService"),
  UserSubscriptionService: require("./UserSubscriptionService"),
  TransactionService: require("./TransactionService"),
  CommonService: require("./CommonService"),
  CartService: require("./CartService"),
  ContactUsService: require("./ContactUsService"),
  SocialMediaService: require("./SocialMediaService"),
};
